@echo off
echo Loading env variables from common .env file in local execution...
for /F "tokens=1* delims==" %%a in (..\common\.env) do ( set "%%a=%%b" )
echo Running Game AI Worker with model %IMAGE_MODEL_NAME%...
python imagecreator.py
