version: "3"
services:
  gameserver:
    image: gameserver
    ports:
      - "3001:3001"
  frontend:
    image: frontend
    ports:
      - "3000:3000"
  aibroker:
    image: aibroker
    environment:
      #This is for local integrated testing
      - GAMESERVER_HOSTNAME=gameserver
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_COUNT=${AI_COUNT}
