@echo off
echo Loading env variables from common .env file in local execution...
for /F "tokens=1* delims==" %%a in (..\common\.env) do ( set "%%a=%%b" )
echo Running AI Requester with model %MODEL_NAME%...
set MODEL_SYSTEM_MESSAGE=
python airequester.py
