name: run-unit-tests
run-name: ${{ github.actor }} is running unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"
      - run: pip install -r gameserver/requirements.txt
      - run: cd gameserver; python -m unittest test_gameserver
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: gameserver/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gameserver:latest
