name: run-unit-tests
run-name: ${{ github.actor }} is running unit tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"
      - run: ls -R
      - run: cd gameserver
      - run: python -m unittest gameserver.test_gameserver
